if [ "$(tty)" = "/dev/tty1" ]; then
    /home/zero/soundCheck/guest/rpi-rgb-led-matrix-master/utils/gif-and-text-api \
  --led-rows=64 \
  --led-cols=64 \
  --led-chain=1 \
  --led-slowdown-gpio=2 \
  --led-brightness=80 \
  --led-gpio-mapping=adafruit-hat-pwm \
  --json-url=http://192.168.178.100:4567/api/info \
  --gif-url=http://192.168.178.100:4567/api/art/cover.gif \
  --keys=song,artist,album,year \
  --font=/home/zero/soundCheck/guest/rpi-rgb-led-matrix-master/fonts/font.bdf \
  --idle-image=/home/zero/soundCheck/guest/idle-small.gif \
  --text-bar-height=8 \
  --scroll-speed=2 \
  --gif-speed=900 \
  --poll-ms=3000
fi