include ../config.mk

CXXFLAGS=-O3 $(CPU_ARCH_FLAGS) $(LTO_FLAGS) -W -Wall -Wextra -Wno-unused-parameter -D_FILE_OFFSET_BITS=64 -std=c++11

RGB_LIB_DISTRIBUTION=..
RGB_INCDIR=$(RGB_LIB_DISTRIBUTION)/include
RGB_LIBDIR=$(RGB_LIB_DISTRIBUTION)/lib
RGB_LIBRARY_NAME=rgbmatrix
RGB_LIBRARY=$(RGB_LIBDIR)/lib$(RGB_LIBRARY_NAME).a
RGB_LDFLAGS+=$(CPU_ARCH_FLAGS) $(LTO_FLAGS) -L$(RGB_LIBDIR) -l$(RGB_LIBRARY_NAME) -lrt -lm -lpthread

MAGICK_CXXFLAGS?=$(shell GraphicsMagick++-config --cppflags --cxxflags)
MAGICK_CXXFLAGS := $(filter-out -Werror=implicit-function-declaration,$(MAGICK_CXXFLAGS))
MAGICK_LDFLAGS?=$(shell GraphicsMagick++-config --ldflags --libs)
CURL_CXXFLAGS?=$(shell pkg-config --cflags libcurl)
CURL_LDFLAGS?=$(shell pkg-config --libs libcurl)

SOURCE=../../gif_and_text_api.cc
OBJECT=gif_and_text_api.o
BINARY=gif-and-text-api

all: $(BINARY)

$(RGB_LIBRARY): FORCE
	$(MAKE) -C $(RGB_LIBDIR)

$(BINARY): $(OBJECT) $(RGB_LIBRARY)
	$(CXX) $(CXXFLAGS) $(OBJECT) -o $@ $(LDFLAGS) $(RGB_LDFLAGS) $(MAGICK_LDFLAGS) $(CURL_LDFLAGS)

$(OBJECT): $(SOURCE)
	$(CXX) -I$(RGB_INCDIR) $(CXXFLAGS) $(MAGICK_CXXFLAGS) $(CURL_CXXFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJECT) $(BINARY)

FORCE:
.PHONY: FORCE all clean
